[deploy]
bucket = 'marcus0423-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:949461172049:certificate/0db07f33-99ed-42ee-bf0d-da42613fee1b'
NetworkingStack = 'CrdNet'